### ISSUE TITLE
Suggested improvements

### ISSUE THREAD

**Issue by mattrayner** [ukparliament/parliament-ntriple#1]
## Readme
Should we mention that this is effectively an add-on for parliament-ruby and link back to it?

Requirements is linking to grom decorators?

Line | Comment
---|---
https://github.com/ukparliament/parliament-ntriple/blob/master/lib/parliament/builder/ntriple_response_builder.rb#L3 | It's not technically API specific?
https://github.com/ukparliament/parliament-ntriple/blob/master/lib/parliament/builder/ntriple_response_builder.rb#L5 | this creates a Parliament::Builder::NTri...
https://github.com/ukparliament/parliament-ntriple/blob/master/lib/parliament/builder/ntriple_response_builder.rb#L7 | This should be on the class?
https://github.com/ukparliament/parliament-ntriple/blob/master/lib/parliament/builder/ntriple_response_builder.rb#L12 | Technically this takes a Module? It's not gem specific? Should this cause an example too?
https://github.com/ukparliament/parliament-ntriple/blob/master/lib/parliament/builder/ntriple_response_builder.rb#L24 | Would this syntax be nicer as `@decorators.decorate(object)`? Also - should this line be `objects = objects.map ...`? Where is the map going? I think you mean `map!`?
https://github.com/ukparliament/parliament-ntriple/blob/master/lib/parliament/response/ntriple_response.rb#L5 | API specific?

**Comment by katylouise** [comment]
Addressed all the comments above in my most recent commits.
